### PR TITLE
Ignore outrageously large files from source bundles

### PR DESCRIPTION
**Pull request by donalmacc**
Fixes https://github.com/getsentry/symbolicator/issues/1217 by ignoring PCH's

### CODE REVIEW

**Review by loewenheim — APPROVED** [review]

**Comment by loewenheim** [comment]
This still requires some linting fixes, and a changelog entry would be appreciated :)

**Comment by donalmacc** [comment]
Hey and sorry about the delay here. I added a changelog entry (but I picked a version number, not sure what the norm is here).

Regarding the linting fixes, I'm happy to apply them, but I actually don't understand what the problem is. When I run `cargo fmt --all -- --check` locally it seems fine, and the link doesn't seem to show any errors, just the diff of my changes. I'm happy to change them if I can figure out what's wrong though.

**Comment by loewenheim** [comment]
Can you try running `cargo fmt --all` (without `--check`) and see if it modifies anything?

**Comment by donalmacc** [comment]
Thanks for handling this, sorry. This has been on the backburner for me the last few weeks and I kept meaning to come back to it.

**Comment by loewenheim** [comment]
No problem, thanks for making the PR!

**Pull request merged**
