### PR TITLE
ref: Thread `CfiCacheModules` through iterative stackwalking

### PR DESCRIPTION
**Pull request by Swatinem**
This was an experiment trying to thread `CfiCacheModules` through iterative stackwalking, with the aim of eventually merging it with `ModuleListBuilder` and `SymbolicatorSymbolProvider` to avoiding re-parsing of already parsed cfi caches (which is expensive).

Not sure this experiment was worth it though. There is a ton of work ahead to make this code better.

#skip-changelog

### CODE REVIEW

**Review by loewenheim — COMMENTED** [review]
The one thing I don't like about this is the addition of `cfi_caches` to `StackwalkMinidumpResult`. AFAICT the result is never interesting, it's always exactly what was passed into `stackwalk`. Does `stackwalk` need to take `cfi_caches` by value?

**Comment by Swatinem** [comment]
> Does `stackwalk` need to take `cfi_caches` by value?

It does, because of the task being spawned on another runtime. Essentially what I complained about during the meetings yesterday :-(

**Comment by Swatinem** [comment]
That said, we have a jira ticket tracking the iterative vs async stack walking, though the thing that causes problems here specifically is crossing the async runtime boundaries :-(

**Comment by Swatinem** [comment]
#838 makes this fully async so this is not needed anymore

**Pull request closed without merging**
