### PR TITLE
ref: Remove breakpad stackwalking code (NATIVE-522)

### PR DESCRIPTION
**Pull request by Swatinem**
This is on top of #723, and completely removes breakpad from the codebase, and the build.

As this switches from breakpad to rust-minidump by default, the effect on a quick `wrk` shows that rps went from ~270 to ~360 for a very nice win.

### CODE REVIEW

**Comment by Swatinem** [comment]
The snapshots have these changes, as I now append the `crash_address` to the type/message.

```
-    type: EXCEPTION_ACCESS_VIOLATION_WRITE
-    value: 'Fatal Error: EXCEPTION_ACCESS_VIOLATION_WRITE'
+    type: EXCEPTION_ACCESS_VIOLATION_WRITE / 0x45
+    value: 'Fatal Error: EXCEPTION_ACCESS_VIOLATION_WRITE / 0x45'
```

**Comment by Swatinem** [comment]
This is now blocked by https://github.com/getsentry/sentry/pull/32871

**Review by flub — COMMENTED** [review]
can't wait to see this merged :)

**Review by loewenheim — APPROVED** [review]

**Comment by Gankra** [comment]
😸🎉

**Review by flub — APPROVED** [review]
🎉

**Pull request merged**
