### PR TITLE
feat(casing): Added SSQP directory layout support

### LINKED ISSUE #35: Implement Two Tier Storage Format (index2.txt)
Microsoft Symbol Server can indicate to clients through the presence of an `index2.txt` file in the root, that [two tier storage](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symbol-store-folder-tree) is used.

Single tier:

```
D:\SymStore\Symbols\ntdll.dll\...\
D:\SymStore\Symbols\ntdll.pdb\...\
D:\SymStore\Symbols\kernel32.dll\...\
D:\SymStore\Symbols\kernel32.pdb\...\
```

Multi tier:

```
D:\SymStore\Symbols\nt\ntdll.dll\...\
D:\SymStore\Symbols\nt\ntdll.pdb\...\
D:\SymStore\Symbols\ke\kernel32.dll\...\
D:\SymStore\Symbols\ke\kernel32.pdb\...\
```

### LINKED ISSUE #36: Better Casing Control for SymStore
SSQP wants the signature to be lowercase except for age which is uppercase. We currently use breakpad which is uppercase except age is lowercase.

I believe we need these options to work in the real world for the signature:

* PDB signature:
  * all uppercase (unity, case sensitive)
  * lowercase with uppercase age (what SSQP wants but doesn't emit)
  * all lowercase (what we already have and what SSQP emits -.-)
* PE signature:
  * uppercase then lowercase (unity, case sensitive)
  * lowercase entirely (what SSQP wants and emits)

Maybe these values would make sense in addition to `default`, `lowercase` and `uppercase`:

* `symstore`: PDB signature all uppercase, PE signature uppercase than lowercase
* `ssqp`: all lowercase with uppercase age for PDB

😒

### PR DESCRIPTION
**Pull request by mitsuhiko**
This improves SSQP/SymStore compatibility by implementing the
different casing rules for signatures and pdb filenames for
SymStore and SSQP.  There are many existing SymStores like Unity
and Google that are stored on case sensitive file systems and as
such need the exact casing rules that the Microsoft client sends.

These are not the rules that SSQP defines.  As such this now
adds a second layout to control them.

Fixes #36
Fixes #35

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I can't read why these tests are failing. @untitaker is there a way to make this diff less confusing?

**Comment by untitaker** [comment]
I added a pytest extension because I thought the default pytest diff is really bad with json, but the side-by-side diff also has its problems. You can remove `pytest-icdiff` from the Makefile.

All I read from here is that it was unable to find some debug images now from the ms symstore.

**Comment by mitsuhiko** [comment]
Running locally after last commit I get these changes:

```
  'sym_addr': '0x76e75d90',
  -                               'symbol': 'NlsIsUserDefaultLocale'}],
  +                               'symbol': 'NlsIsUserDefaultLocale@4'}],
  ?                                                                ++
```

**Comment by untitaker** [comment]
This seems fine but I have no idea what it is caused by.

**Comment by untitaker** [comment]
@mitsuhiko this passes for me locally

**Pull request merged**
