### PR TITLE
Upgrade wasmbin

### PR DESCRIPTION
**Pull request by RReverser**
wasmbin had various improvements to the API and the docs, including addition of few more "well-known" custom sections since, so this simplifies the code quite a bit.

Unfortunately, I didn't find any tests so would leave it up to the reviewer.

#skip-changelog

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]
Thank you!

I’m a bit surprised this does not conflict though, as I recently updated to `0.5.0` in https://github.com/getsentry/symbolicator/commit/10f17846b1295c8de851173d214823f053ae14eb

**Comment by Swatinem** [comment]
Oh well, it indeed conflicts :-D

**Comment by RReverser** [comment]
Oh woops, I started this PR earlier, but then noticed few more potential improvements for wasmbin, added them and didn't rebase 😅

Didn't realise you made another update meanwhile, sorry.

**Comment by RReverser** [comment]
Rebased, most of the code simplification remains :)

**Pull request merged**
