### PR TITLE
BCSymbolMap support in symbolicator

### PR DESCRIPTION
**Pull request by flub**
~~So far adds support to symsorter, not nice code at all yet, but it works.~~

### CODE REVIEW

**Review by Swatinem — COMMENTED** [review]
lgtm so far. Would be nice to extract some unrelated refactoring out of this PR

**Comment by flub** [comment]
Currently no attempt is done to invalidate the symcache if one was created earlier with no BCSymbolMap but later a BCSymbolMap became available.

**Review by Swatinem — APPROVED** [review]

**Comment by flub** [comment]
> lgtm so far. Would be nice to extract some unrelated refactoring out of this PR

This is true, the changes in the object actor are not really needed (apart from moving decompression to a utility) and only there as i was originally was trying to use the object actor.  Some changes I don't care about (the data_cache) but some I'd like to keep as I think it makes it simpler (the meta_cache changes)

**Comment by flub** [comment]
PTAL, now plist parsing has moved back to symbolic.  This PR is basically ready.

**Review by Swatinem — APPROVED** [review]

**Pull request merged**
