### PR TITLE
feat(metrics): Add platform tag

### LINKED ISSUE #1509: Tag symbolicator metrics with `symbolicator_platform` (or `platform`) tags
We don't really have good ways of separating metrics for the various platforms that we now support in symbolicator (eg. native, js, jvm). We have `hostname` tags which let us split metrics at the pod level (symbolicator-0, symbolicator-1, symbolicator-js-0, symbolicator-js-1, ...)

However this is not very useful for visualizing or alerting on the platform performance in aggregate - eg. alert when `max(requests.inflight by platform) > 180 for 30m`. Or adding an "average requests in flight" count per platform rather than this mess:

Image

I always kind of assume there would be separate sections for each symbolicator type in our main dashboard, but I guess not having these tags would be why.

### PR DESCRIPTION
**Pull request by loewenheim**
This adds a configurable platform tag to metrics. If this is set, the platform ~(determined based on the Symbolicator's hostname)~ (read from the `SYMBOLICATOR_PLATFORM` env variable) will be reported with every metric.

Fixes #1509.

### CODE REVIEW

**Comment by mwarkentin** [comment]
@loewenheim just saw this, I will try to take a look. I wonder if there's anything we could do by setting an extra environment variable which could contain a platform tag value. Would this be better than the host name parsing?

**Comment by loewenheim** [comment]
> @loewenheim just saw this, I will try to take a look. I wonder if there's anything we could do by setting an extra environment variable which could contain a platform tag value. Would this be better than the host name parsing?

Sorry for the late answer. From the Symbolicator code perspective it would be simple—we can just read the value of an environment variable. How complicated would it be from the configuration point of view?

**Comment by mwarkentin** [comment]
@loewenheim pretty easy (I think): https://github.com/getsentry/ops/pull/11922

**Comment by loewenheim** [comment]
I was under the impression that the platform should just be `js`, `jvm`, or `native`. But in any case, it sounds like an env var is the way to go.

**Review by Dav1dde — APPROVED** [review]

**Comment by mwarkentin** [comment]
@loewenheim ill try to get these rolled out everywhere tomorrow.

**Comment by mwarkentin** [comment]
@loewenheim env vars have been configured on:

* s4s
* geico
* goldmansachs
* disney
* ly
* de
* saas (us)

**Pull request merged**
