### PR TITLE
ref: Unify SymbolicationActor impl blocks

### PR DESCRIPTION
**Pull request by loewenheim**
I sometimes wish you could write your own diffs—this is absolutely incomprehensible. Long story short, `SymbolicationActor` hat several impl blocks, I put everything in one.

#skip-changelog

### CODE REVIEW

**Review by Swatinem — COMMENTED** [review]
I actually like this to be separated by topic, I would even go further and put things into different files related to stack unwinding, or to symbolication of existing stack traces, vs other stuff.

**Comment by loewenheim** [comment]
Yeah, I can see that. With this change, it's easier to find all methods, but the impl block is massive, which causes its own issues.

**Comment by flub** [comment]
I agree with the multiple files thing.  But probably also not all attached to one common struct even.  In either case, that doesn't have to stop this.  I'm +0 on this change: I don't mind it but I also never felt the need enough to bother doing it myself.

**Review by flub — APPROVED** [review]

**Comment by loewenheim** [comment]
If you're neutral and Árpád is against, I'd rather shelve it until we have a refactoring that we're actually happy with.

**Pull request closed without merging**
