### PR TITLE
Add --strip-names option to wasm-split

### PR DESCRIPTION
**Pull request by samsartor**
The `--strip` option of wasm-split leaves symbol names intact. Specifically, it does not remove the ["name" custom section
](https://webassembly.github.io/spec/core/appendix/custom.html#name-section). This may be desired in some cases, but it significantly increases the size of the wasm bundle and potentially leaks source info to users.

This PR adds a `--strip-names` flag to remove the "name" section as well.

I considered adding a flag (e.g. `--strip-by [NAME]`) to strip arbitrary custom sections matching NAME (which confusingly, could be "name"), but decided against it. Let me know if that would be preferable.

I haven't yet had the chance to verify that our wasm bundle still works with sentry itself after removing the name section, but I'm guessing it will. I won't merge here until that is tested, but I figured it would be good to get reviewed ASAP.

### CODE REVIEW

**Comment by samsartor** [comment]
I couldn't find a contributing guide for this repo, so I just did my best. It seems like there is some naming convention needed for CI? @flub what should I do to adhear to that?

**Review by flub — APPROVED** [review]

**Comment by flub** [comment]
@samsartor CI is happy, the Danger action is trying to be smart and ask for a changelog entry if necessary (there is no changelog for wasm-split, so not needed I'd say).  However it fails because it tries to get permission to post to this PR but doesn't have access to the secret of this repo.  We should fix that :(

**Comment by samsartor** [comment]
Alas, Sentry is barfing a little bit on our wasm bundle. I think I have a fix for that here: https://github.com/rustwasm/walrus/pull/209. However, this change appears to be working as intended! I'm ready for it to be merged as soon as y'all are.

**Comment by jan-auer** [comment]
Thanks, overriding status checks and adding a changelog entry on master directly.

**Pull request merged**
